### PR TITLE
Added a factor of 2 for RAM_wordlinedriver_area in fpga.py, line 5768 since there are 2 wordlines (1 for each port) per BRAM row. 

### PR DESCRIPTION
**Pull request by yc2367**
Modification based on issue #36

### CODE REVIEW

**Comment by vaughnbetz** [comment]
Looks good; could you also add to the comment that the two wordline drivers per row is due to having two ports?

**Comment by vaughnbetz** [comment]
@sadegh68 @aman26kbm : FYI.

**Comment by yc2367** [comment]
I have added comments in fpga.py, line 5768

**Comment by vaughnbetz** [comment]
Great, thanks!

**Pull request merged**
